# fly.toml app configuration file generated for jabber on 2023-07-03T10:20:09-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "jabber"
primary_region = "dfw"



[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
