export { default as Main } from './Main';
export { default as Home } from './Home';
export { default as Header } from './Header';
export { default as Register } from './Register';
export { default as Me } from './Me';
export { default as Posts } from './Posts';
export { default as AddPost } from './AddPost';
export { default as Profile } from './Profile';
export { default as Messages } from './Messages';